# Generated by Django 5.2.1 on 2025-06-30 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
